// ===========================================================================
// foods-data.ts — cơ sở dữ liệu thực phẩm Việt cho tính toán dinh dưỡng thai kỳ.
// Mỗi thực phẩm: dinh dưỡng trên 100 g phần ăn được (giá trị tham khảo) + cờ an toàn.
// Thuần TS (không import `@/`, không dependency) để self-check chạy bằng node đơn lẻ.
//
// NGUỒN SỐ LIỆU (theo nhóm):
//  - Rau / củ / quả: Bảng thành phần thực phẩm Việt Nam (Viện Dinh dưỡng, 2007)
//    cho thực phẩm VN; riêng một số rau nhiệt đới (rau ngót, rau muống, mồng tơi,
//    rau dền...) và các thực phẩm đã ghi `sourceNote` dùng số liệu Bảng TP VN 2007.
//  - Thịt / trứng / cá / hải sản: USDA FDC (cooked, edible) — Bảng TP VN chủ yếu
//    số liệu sống/chưa nấu nên giữ USDA cho nhóm nấu chín.
//  - Sữa & chế phẩm: USDA FDC (dạng tươi/nguyên kem).
//  - Đậu / hạt / nấm: USDA FDC; đậu phụ tính theo loại đông đặc bằng canxi.
//  - Ngũ cốc: Bảng thành phần TP VN 2007 cho gạo/bún/phở/bánh mì/ngô;
//    USDA FDC cho các loại còn lại.
//  - Gia vị: giá trị tham khảo; nước mắm theo Bảng TP VN 2007; muối i-ốt theo
//    hàm lượng tăng cường ~25–30 mg/kg.
//
// Giá trị là THAM KHẢO, có thể lệch theo mùa/vùng/giống. Các thực phẩm ghi
// `accuracy: 'VN-KB'` lấy số liệu Bảng thành phần thực phẩm VN (Bộ Y tế —
// Viện Dinh dưỡng) bản 2007. Chi tiết đối chiếu: docs/vietnam-food-composition-notes.md.
// ===========================================================================

// ---- Kiểu dữ liệu ----
export type FoodGroup =
  | 'rau'
  | 'thit'
  | 'ca-hai-san'
  | 'trung-sua'
  | 'ngu-coc'
  | 'trai-cay'
  | 'dau-hat'
  | 'gia-vi'

export const FOOD_GROUPS: readonly FoodGroup[] = [
  'rau',
  'thit',
  'ca-hai-san',
  'trung-sua',
  'ngu-coc',
  'trai-cay',
  'dau-hat',
  'gia-vi',
]

export type FoodAccuracy = 'USDA' | 'estimate' | 'VN-KB'

export const FOOD_ACCURACIES: readonly FoodAccuracy[] = ['USDA', 'estimate', 'VN-KB']

/** Dinh dưỡng trên 100 g phần ăn được. */
export interface FoodNutrition {
  /** Năng lượng, kcal */
  kcal: number
  /** Đạm, g */
  protein: number
  /** Carbohydrate, g */
  carb: number
  /** Chất béo, g */
  fat: number
  /** Chất xơ, g */
  fiber: number
  /** Sắt, mg */
  iron: number
  /** Canxi, mg */
  calcium: number
  /** Folate, mcg (DFE) */
  folate: number
  /** Vitamin C, mg */
  vitaminC: number
  /** Vitamin D, mcg (IU/40) */
  vitaminD: number
  /** Kẽm, mg */
  zinc: number
  /** I-ốt, mcg */
  iodine: number
  /** Omega-3 (EPA+DHA), mg */
  omega3: number
  /** Natri, mg */
  sodium: number
  /** Đường, g */
  sugar: number
}

/** Cờ an toàn thai kỳ (tham khảo ACOG/NHS/FDA-EPA/KB GĐ2). */
export interface FoodSafety {
  /** Tránh khi mang thai (thủy ngân cao, retinol cao...). */
  avoid?: boolean
  /** Ăn hạn chế (về lượng/tần suất). */
  limit?: boolean
  /** Phải nấu chín trước khi ăn (không ăn sống). */
  cook?: boolean
  /** Lý do ngắn (hiển thị trong app). */
  reason?: string
}

export interface FoodItem {
  /** Khóa ổn định — các món ăn tham chiếu theo id này. */
  id: string
  /** Tên tiếng Việt. */
  name: string
  /** Tên tham khảo tiếng Anh (nếu có). */
  nameEn?: string
  group: FoodGroup
  per100g: FoodNutrition
  accuracy: FoodAccuracy
  /** Ghi chú nguồn / trạng thái (sống-chín). */
  sourceNote: string
  safety: FoodSafety
}

/** Hàm dựng dinh dưỡng — các trường bỏ qua mặc định = 0. */
function n(p: Partial<FoodNutrition>): FoodNutrition {
  return {
    kcal: 0,
    protein: 0,
    carb: 0,
    fat: 0,
    fiber: 0,
    iron: 0,
    calcium: 0,
    folate: 0,
    vitaminC: 0,
    vitaminD: 0,
    zinc: 0,
    iodine: 0,
    omega3: 0,
    sodium: 0,
    sugar: 0,
    ...p,
  }
}

// ===========================================================================
// DỮ LIỆU — 132 thực phẩm Việt
// ===========================================================================
export const FOODS: FoodItem[] = [
  // -------------------------------------------------------------------------
  // 1. RAU, CỦ, QUẢ (32)
  // -------------------------------------------------------------------------
  {
    id: 'rau-ngot',
    name: 'Rau ngót (bồ ngót)',
    nameEn: 'Sauropus androgynus',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — rau ngót; sắt 2,7 · vitC 185 · canxi 169.',
    per100g: n({ kcal: 35, protein: 5.3, carb: 3.4, fat: 0.5, fiber: 2.5, iron: 2.7, calcium: 169, folate: 150, vitaminC: 185, zinc: 0.94, sodium: 25, sugar: 1 }),
    safety: { cook: true, reason: 'Nấu chín trước khi ăn; không uống nước rau ngót sống (tranh cãi dân gian).' },
  },
  {
    id: 'rau-muong',
    name: 'Rau muống',
    nameEn: 'Water spinach (Ipomoea aquatica)',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — rau muống.',
    per100g: n({ kcal: 25, protein: 3.2, carb: 2.1, fat: 0.4, fiber: 1.0, iron: 1.4, calcium: 100, folate: 194, vitaminC: 23, zinc: 0.35, sodium: 37, sugar: 0.7 }),
    safety: { cook: true, reason: 'Nấu chín; rau muống nước có nguy cơ nhiễm sán — rửa kỹ, nấu kỹ.' },
  },
  {
    id: 'cai-bxo',
    name: 'Cải bó xôi (rau chân vịt)',
    nameEn: 'Spinach (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 168462 (cooked) — giàu sắt, folate, canxi.',
    per100g: n({ kcal: 23, protein: 3, carb: 3.8, fat: 0.3, fiber: 2.4, iron: 3.6, calcium: 136, folate: 194, vitaminC: 28, zinc: 0.76, sodium: 70, sugar: 0.4 }),
    safety: { cook: true, reason: 'Luộc/xào chín trước khi ăn.' },
  },
  {
    id: 'cai-thao',
    name: 'Cải thìa',
    nameEn: 'Bok choy',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169983 (raw).',
    per100g: n({ kcal: 13, protein: 1.5, carb: 2.2, fat: 0.2, fiber: 1, iron: 0.8, calcium: 105, folate: 66, vitaminC: 45, zinc: 0.3, sodium: 65, sugar: 1.2 }),
    safety: { cook: true },
  },
  {
    id: 'cai-ngot',
    name: 'Cải ngọt',
    nameEn: 'Choy sum / Chinese flowering cabbage',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — cải xanh (cải ngọt).',
    per100g: n({ kcal: 16, protein: 1.7, carb: 1.9, fat: 0.2, fiber: 1.8, iron: 1.9, calcium: 89, folate: 187, vitaminC: 51, zinc: 0.9, sodium: 29, sugar: 1 }),
    safety: { cook: true },
  },
  {
    id: 'bap-cai',
    name: 'Bắp cải',
    nameEn: 'Cabbage',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — cải bắp.',
    per100g: n({ kcal: 29, protein: 1.8, carb: 5.3, fat: 0.1, fiber: 1.6, iron: 1.1, calcium: 48, folate: 43, vitaminC: 30, zinc: 0.81, sodium: 28, sugar: 3.2 }),
    safety: {},
  },
  {
    id: 'sup-lo-xanh',
    name: 'Súp lơ xanh (bông cải xanh)',
    nameEn: 'Broccoli (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170383 (cooked) — folate 108 · vitC 89 (KB).',
    per100g: n({ kcal: 35, protein: 2.4, carb: 7.2, fat: 0.4, fiber: 3.3, iron: 1, calcium: 47, folate: 108, vitaminC: 89, zinc: 0.4, sodium: 41, sugar: 1.4 }),
    safety: { cook: true },
  },
  {
    id: 'sup-lo-trang',
    name: 'Súp lơ trắng',
    nameEn: 'Cauliflower',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169986 (raw).',
    per100g: n({ kcal: 25, protein: 1.9, carb: 5, fat: 0.3, fiber: 2, iron: 0.4, calcium: 22, folate: 44, vitaminC: 46, zinc: 0.3, sodium: 30, sugar: 1.9 }),
    safety: {},
  },
  {
    id: 'muong-toi',
    name: 'Mồng tơi',
    nameEn: 'Malabar spinach',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — mồng tơi.',
    per100g: n({ kcal: 14, protein: 2.0, carb: 1.4, fat: 0.3, fiber: 2.5, iron: 1.6, calcium: 176, folate: 45, vitaminC: 72, zinc: 0.54, sodium: 38, sugar: 1 }),
    safety: { cook: true },
  },
  {
    id: 'rau-den',
    name: 'Rau dền',
    nameEn: 'Amaranth leaves (red)',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — rau dền đỏ (giàu sắt & canxi).',
    per100g: n({ kcal: 41, protein: 3.3, carb: 6.2, fat: 0.3, fiber: 1.6, iron: 5.4, calcium: 288, folate: 85, vitaminC: 89, zinc: 0.5, sodium: 56, sugar: 0.4 }),
    safety: { cook: true },
  },
  {
    id: 'xa-lach',
    name: 'Xà lách',
    nameEn: 'Lettuce',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169247 (iceberg, raw).',
    per100g: n({ kcal: 15, protein: 1.4, carb: 2.9, fat: 0.2, fiber: 1.3, iron: 0.9, calcium: 36, folate: 38, vitaminC: 9, zinc: 0.2, sodium: 28, sugar: 0.8 }),
    safety: { reason: 'Rau ăn sống cần rửa kỹ từng lá; hạn chế rau sống ngoài hàng quán.' },
  },
  {
    id: 'cai-xoong',
    name: 'Cải xoong',
    nameEn: 'Watercress',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169264 (raw).',
    per100g: n({ kcal: 11, protein: 2.3, carb: 1.3, fat: 0.1, fiber: 0.5, iron: 0.2, calcium: 120, folate: 13, vitaminC: 43, zinc: 0.1, sodium: 41, sugar: 0.2 }),
    safety: { cook: true, reason: 'Cải xoong sống ở nước có nguy cơ sán — nấu chín.' },
  },
  {
    id: 'rau-thom',
    name: 'Rau thơm (hỗn hợp)',
    nameEn: 'Fresh herbs (mix)',
    group: 'rau',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo mức trung bình rau thơm VN (húng, tía tô, ngổ...).',
    per100g: n({ kcal: 20, protein: 1.5, carb: 3, fat: 0.3, fiber: 1.5, iron: 1, calcium: 60, folate: 30, vitaminC: 20, zinc: 0.3, sodium: 20, sugar: 1 }),
    safety: { reason: 'Rau sống cần rửa kỹ, ngâm muối.' },
  },
  {
    id: 'hung-que',
    name: 'Húng quế',
    nameEn: 'Thai basil',
    group: 'rau',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo USDA sweet basil.',
    per100g: n({ kcal: 23, protein: 3.2, carb: 2.7, fat: 0.6, fiber: 1.6, iron: 2, calcium: 180, folate: 68, vitaminC: 18, zinc: 0.8, sodium: 4, sugar: 0.3 }),
    safety: {},
  },
  {
    id: 'rau-mui',
    name: 'Rau mùi (ngò rí)',
    nameEn: 'Coriander / cilantro',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169913 (raw).',
    per100g: n({ kcal: 23, protein: 2.1, carb: 3.7, fat: 0.5, fiber: 2.8, iron: 1.8, calcium: 67, folate: 62, vitaminC: 27, zinc: 0.5, sodium: 46, sugar: 0.9 }),
    safety: {},
  },
  {
    id: 'hanh-la',
    name: 'Hành lá',
    nameEn: 'Scallion / green onion',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170004 (raw).',
    per100g: n({ kcal: 32, protein: 1.8, carb: 7.3, fat: 0.2, fiber: 2.6, iron: 1.5, calcium: 72, folate: 64, vitaminC: 18.8, zinc: 0.4, sodium: 16, sugar: 2.3 }),
    safety: {},
  },
  {
    id: 'ca-rot',
    name: 'Cà rốt',
    nameEn: 'Carrot (raw)',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — cà rốt (beta-caroten cao, tiền vitamin A an toàn).',
    per100g: n({ kcal: 39, protein: 1.5, carb: 7.8, fat: 0.2, fiber: 1.2, iron: 0.8, calcium: 43, folate: 19, vitaminC: 8, zinc: 1.11, sodium: 52, sugar: 4.7 }),
    safety: {},
  },
  {
    id: 'bi-do',
    name: 'Bí đỏ (bí ngô)',
    nameEn: 'Pumpkin (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169147 (boiled) — beta-caroten cao.',
    per100g: n({ kcal: 20, protein: 0.7, carb: 5, fat: 0.1, fiber: 1.1, iron: 0.6, calcium: 15, folate: 9, vitaminC: 4.7, zinc: 0.3, sodium: 1, sugar: 2.1 }),
    safety: {},
  },
  {
    id: 'bi-dao',
    name: 'Bí đao',
    nameEn: 'Winter melon',
    group: 'rau',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng — bí đao VN.',
    per100g: n({ kcal: 13, protein: 0.4, carb: 3, fat: 0.1, fiber: 1, iron: 0.2, calcium: 19, folate: 4, vitaminC: 13, zinc: 0.6, sodium: 111, sugar: 3 }),
    safety: { cook: true },
  },
  {
    id: 'muop',
    name: 'Mướp hương',
    nameEn: 'Luffa / sponge gourd',
    group: 'rau',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng.',
    per100g: n({ kcal: 18, protein: 0.5, carb: 4, fat: 0.1, fiber: 1.4, iron: 0.2, calcium: 20, folate: 18, vitaminC: 14, zinc: 0.2, sodium: 3, sugar: 1.5 }),
    safety: { cook: true },
  },
  {
    id: 'dua-chuot',
    name: 'Dưa chuột',
    nameEn: 'Cucumber',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169252 (raw, with peel).',
    per100g: n({ kcal: 15, protein: 0.7, carb: 3.6, fat: 0.1, fiber: 0.5, iron: 0.3, calcium: 16, folate: 7, vitaminC: 2.8, zinc: 0.2, sodium: 2, sugar: 1.7 }),
    safety: { reason: 'Rửa kỹ, gọt vỏ nếu ăn sống.' },
  },
  {
    id: 'ca-chua',
    name: 'Cà chua',
    nameEn: 'Tomato',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — cà chua (lycopene).',
    per100g: n({ kcal: 20, protein: 0.6, carb: 4.0, fat: 0.2, fiber: 0.8, iron: 1.4, calcium: 12, folate: 15, vitaminC: 40, zinc: 0.74, sodium: 12, sugar: 2.6 }),
    safety: {},
  },
  {
    id: 'ca-tim',
    name: 'Cà tím',
    nameEn: 'Eggplant',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169282 (raw).',
    per100g: n({ kcal: 25, protein: 1, carb: 6, fat: 0.2, fiber: 3, iron: 0.2, calcium: 9, folate: 22, vitaminC: 2.2, zinc: 0.2, sodium: 2, sugar: 3.5 }),
    safety: {},
  },
  {
    id: 'su-su',
    name: 'Su su',
    nameEn: 'Chayote',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — su su (folate cao).',
    per100g: n({ kcal: 19, protein: 0.8, carb: 3.6, fat: 0.1, fiber: 1.0, iron: 0.4, calcium: 17, folate: 93, vitaminC: 4, zinc: 0.74, sodium: 2, sugar: 1.7 }),
    safety: { cook: true },
  },
  {
    id: 'gia-do',
    name: 'Giá đỗ',
    nameEn: 'Mung bean sprouts',
    group: 'rau',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — giá đỗ xanh.',
    per100g: n({ kcal: 44, protein: 5.5, carb: 5.1, fat: 0.2, fiber: 2.0, iron: 1.4, calcium: 38, folate: 61, vitaminC: 10, zinc: 0.41, sodium: 23, sugar: 4.1 }),
    safety: { cook: true, reason: 'Giá sống nguy cơ nhiễm khuẩn (E.coli/Salmonella) — ăn chín khi mang thai.' },
  },
  {
    id: 'dau-cove',
    name: 'Đậu cô ve (đậu que)',
    nameEn: 'Green beans (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170418 (boiled).',
    per100g: n({ kcal: 31, protein: 1.8, carb: 7, fat: 0.1, fiber: 2.7, iron: 1, calcium: 37, folate: 33, vitaminC: 12, zinc: 0.2, sodium: 6, sugar: 3.3 }),
    safety: { cook: true },
  },
  {
    id: 'kho-qua',
    name: 'Khổ qua (mướp đắng)',
    nameEn: 'Bitter melon',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169926 (raw).',
    per100g: n({ kcal: 17, protein: 1, carb: 3.7, fat: 0.2, fiber: 2.8, iron: 0.4, calcium: 19, folate: 72, vitaminC: 84, zinc: 0.8, sodium: 5, sugar: 2 }),
    safety: { limit: true, reason: 'Khổ qua liều cao có thể hạ đường huyết / kích thích tử cung — ăn ít, nấu chín.' },
  },
  {
    id: 'ot-chuong',
    name: 'Ớt chuông',
    nameEn: 'Bell pepper',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169342 (raw) — vitamin C cao.',
    per100g: n({ kcal: 26, protein: 1, carb: 6, fat: 0.3, fiber: 2.1, iron: 0.3, calcium: 10, folate: 10, vitaminC: 80, zinc: 0.2, sodium: 3, sugar: 4.2 }),
    safety: {},
  },
  {
    id: 'dau-bap',
    name: 'Đậu bắp',
    nameEn: 'Okra (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169418 (boiled) — folate & canxi.',
    per100g: n({ kcal: 33, protein: 1.9, carb: 7.5, fat: 0.2, fiber: 3.2, iron: 0.6, calcium: 82, folate: 60, vitaminC: 23, zinc: 0.6, sodium: 7, sugar: 1.5 }),
    safety: { cook: true },
  },
  {
    id: 'khoai-lang',
    name: 'Khoai lang',
    nameEn: 'Sweet potato (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 168395 (baked) — beta-caroten, chất xơ.',
    per100g: n({ kcal: 90, protein: 2, carb: 20.7, fat: 0.2, fiber: 3.3, iron: 0.7, calcium: 30, folate: 6, vitaminC: 2.4, zinc: 0.4, sodium: 36, sugar: 6.5 }),
    safety: { cook: true },
  },
  {
    id: 'khoai-tay',
    name: 'Khoai tây',
    nameEn: 'Potato (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170113 (boiled) — kali.',
    per100g: n({ kcal: 87, protein: 1.9, carb: 20, fat: 0.1, fiber: 1.8, iron: 0.8, calcium: 12, folate: 9, vitaminC: 13, zinc: 0.4, sodium: 6, sugar: 0.9 }),
    safety: { cook: true },
  },
  {
    id: 'cu-den',
    name: 'Củ dền',
    nameEn: 'Beetroot (cooked)',
    group: 'rau',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169458 (boiled) — folate cao.',
    per100g: n({ kcal: 43, protein: 1.6, carb: 10, fat: 0.2, fiber: 2.8, iron: 0.8, calcium: 16, folate: 109, vitaminC: 4.9, zinc: 0.4, sodium: 78, sugar: 6.8 }),
    safety: { cook: true },
  },

  // -------------------------------------------------------------------------
  // 2. TRÁI CÂY (21)
  // -------------------------------------------------------------------------
  {
    id: 'oi',
    name: 'Ổi',
    nameEn: 'Guava (raw)',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173044 — vitamin C rất cao 228 mg/100g (KB).',
    per100g: n({ kcal: 68, protein: 2.6, carb: 14, fat: 1, fiber: 5.4, iron: 0.3, calcium: 18, folate: 49, vitaminC: 228, zinc: 0.2, sodium: 2, sugar: 9 }),
    safety: { reason: 'Rửa kỹ; gọt vỏ nếu ăn cả quả.' },
  },
  {
    id: 'cam',
    name: 'Cam',
    nameEn: 'Orange (raw)',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — cam (folate & vitamin C).',
    per100g: n({ kcal: 38, protein: 0.9, carb: 8.3, fat: 0.1, fiber: 1.4, iron: 0.4, calcium: 34, folate: 30, vitaminC: 40, zinc: 0.22, sodium: 4, sugar: 9.4 }),
    safety: {},
  },
  {
    id: 'quyt',
    name: 'Quýt',
    nameEn: 'Mandarin',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — quýt.',
    per100g: n({ kcal: 39, protein: 0.8, carb: 8.3, fat: 0.3, fiber: 0.6, iron: 0.4, calcium: 35, folate: 16, vitaminC: 55, zinc: 0.2, sodium: 4, sugar: 10.6 }),
    safety: {},
  },
  {
    id: 'buoi',
    name: 'Bưởi',
    nameEn: 'Pomelo (raw)',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — bưởi (vitamin C).',
    per100g: n({ kcal: 30, protein: 0.2, carb: 7.3, fat: 0, fiber: 0.7, iron: 0.5, calcium: 23, folate: 30, vitaminC: 95, zinc: 0.16, sodium: 3, sugar: 8 }),
    safety: {},
  },
  {
    id: 'chuoi',
    name: 'Chuối',
    nameEn: 'Banana (dwarf, VN)',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — chuối tiêu (kali, xơ).',
    per100g: n({ kcal: 97, protein: 1.5, carb: 22.2, fat: 0.2, fiber: 0.8, iron: 0.6, calcium: 8, folate: 20, vitaminC: 6, zinc: 0.37, sodium: 19, sugar: 12.2 }),
    safety: {},
  },
  {
    id: 'du-du',
    name: 'Đu đủ chín',
    nameEn: 'Papaya (ripe)',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — đu đủ chín (vit C & beta-caroten).',
    per100g: n({ kcal: 36, protein: 1.0, carb: 7.6, fat: 0.1, fiber: 0.6, iron: 2.6, calcium: 40, folate: 38, vitaminC: 54, zinc: 0.1, sodium: 4, sugar: 7.8 }),
    safety: {},
  },
  {
    id: 'xoai',
    name: 'Xoài chín',
    nameEn: 'Mango (ripe)',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — xoài chín (beta-caroten).',
    per100g: n({ kcal: 62, protein: 0.6, carb: 14.1, fat: 0.3, fiber: 1.8, iron: 0.4, calcium: 10, folate: 14, vitaminC: 30, zinc: 0.56, sodium: 2, sugar: 13.7 }),
    safety: {},
  },
  {
    id: 'dua',
    name: 'Dứa (thơm)',
    nameEn: 'Pineapple',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — dứa ta.',
    per100g: n({ kcal: 29, protein: 0.8, carb: 6.5, fat: 0.1, fiber: 0.8, iron: 0.5, calcium: 15, folate: 15, vitaminC: 24, zinc: 0.25, sodium: 24, sugar: 9.9 }),
    safety: {},
  },
  {
    id: 'tao',
    name: 'Táo',
    nameEn: 'Apple',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171688 (with skin).',
    per100g: n({ kcal: 52, protein: 0.3, carb: 13.8, fat: 0.2, fiber: 2.4, iron: 0.1, calcium: 6, folate: 3, vitaminC: 4.6, zinc: 0.1, sodium: 1, sugar: 10.4 }),
    safety: { reason: 'Rửa kỹ trước khi ăn.' },
  },
  {
    id: 'le',
    name: 'Lê',
    nameEn: 'Pear',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169944 (raw).',
    per100g: n({ kcal: 57, protein: 0.4, carb: 15.2, fat: 0.1, fiber: 3.1, iron: 0.2, calcium: 9, folate: 7, vitaminC: 4.3, zinc: 0.1, sodium: 1, sugar: 9.8 }),
    safety: {},
  },
  {
    id: 'nho',
    name: 'Nho',
    nameEn: 'Grapes',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 174680 (raw).',
    per100g: n({ kcal: 69, protein: 0.7, carb: 18.1, fat: 0.2, fiber: 0.9, iron: 0.4, calcium: 10, folate: 2, vitaminC: 10, zinc: 0.1, sodium: 2, sugar: 15.5 }),
    safety: {},
  },
  {
    id: 'mang-cut',
    name: 'Măng cụt',
    nameEn: 'Mangosteen',
    group: 'trai-cay',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng Đông Nam Á.',
    per100g: n({ kcal: 73, protein: 0.4, carb: 18, fat: 0.6, fiber: 1.8, iron: 0.2, calcium: 12, folate: 31, vitaminC: 2.9, zinc: 0.2, sodium: 7, sugar: 16 }),
    safety: {},
  },
  {
    id: 'chom-chom',
    name: 'Chôm chôm',
    nameEn: 'Rambutan',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — chôm chôm.',
    per100g: n({ kcal: 72, protein: 1.5, carb: 16.4, fat: 0, fiber: 1.3, iron: 0.5, calcium: 28, folate: 8, vitaminC: 4.9, zinc: 0.3, sodium: 11, sugar: 17 }),
    safety: {},
  },
  {
    id: 'thanh-long',
    name: 'Thanh long',
    nameEn: 'Dragon fruit',
    group: 'trai-cay',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng — chất xơ, nước.',
    per100g: n({ kcal: 60, protein: 1.2, carb: 13, fat: 0.1, fiber: 3, iron: 0.4, calcium: 18, folate: 27, vitaminC: 9, zinc: 0.2, sodium: 2, sugar: 8 }),
    safety: {},
  },
  {
    id: 'dua-hau',
    name: 'Dưa hấu',
    nameEn: 'Watermelon',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 167765 (raw).',
    per100g: n({ kcal: 30, protein: 0.6, carb: 7.6, fat: 0.2, fiber: 0.4, iron: 0.2, calcium: 7, folate: 3, vitaminC: 8.1, zinc: 0.1, sodium: 1, sugar: 6.2 }),
    safety: {},
  },
  {
    id: 'sau-rieng',
    name: 'Sầu riêng',
    nameEn: 'Durian',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — sầu riêng.',
    per100g: n({ kcal: 132, protein: 2.5, carb: 26.9, fat: 1.6, fiber: 1.4, iron: 0.9, calcium: 20, folate: 36, vitaminC: 37, zinc: 0.28, sodium: 1, sugar: 15 }),
    safety: { limit: true, reason: 'Nhiều năng lượng & đường — ăn ít nếu cần kiểm soát đường huyết.' },
  },
  {
    id: 'vu-sua',
    name: 'Vú sữa',
    nameEn: 'Star apple (caimito)',
    group: 'trai-cay',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng.',
    per100g: n({ kcal: 67, protein: 0.4, carb: 16, fat: 0.6, fiber: 3, iron: 0.3, calcium: 18, folate: 14, vitaminC: 16, zinc: 0.1, sodium: 7, sugar: 11 }),
    safety: {},
  },
  {
    id: 'bo',
    name: 'Bơ',
    nameEn: 'Avocado',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171705 (raw) — chất béo lành mạnh, folate.',
    per100g: n({ kcal: 160, protein: 2, carb: 8.5, fat: 14.7, fiber: 6.7, iron: 0.6, calcium: 12, folate: 81, vitaminC: 10, zinc: 0.6, sodium: 7, sugar: 0.7 }),
    safety: {},
  },
  {
    id: 'chanh',
    name: 'Chanh',
    nameEn: 'Lemon',
    group: 'trai-cay',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 9156 (raw, without peel) — vitamin C.',
    per100g: n({ kcal: 29, protein: 1.1, carb: 9.3, fat: 0.3, fiber: 2.8, iron: 0.6, calcium: 26, folate: 11, vitaminC: 53, zinc: 0.1, sodium: 2, sugar: 2.5 }),
    safety: {},
  },
  {
    id: 'vai',
    name: 'Vải',
    nameEn: 'Lychee',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — vải.',
    per100g: n({ kcal: 45, protein: 0.7, carb: 9.6, fat: 0.4, fiber: 1.1, iron: 0.5, calcium: 6, folate: 14, vitaminC: 36, zinc: 0.07, sodium: 1, sugar: 15.2 }),
    safety: {},
  },
  {
    id: 'nhan',
    name: 'Nhãn',
    nameEn: 'Longan',
    group: 'trai-cay',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — nhãn.',
    per100g: n({ kcal: 48, protein: 0.9, carb: 10.9, fat: 0.1, fiber: 1.0, iron: 0.4, calcium: 21, folate: 0, vitaminC: 58, zinc: 0.29, sodium: 26, sugar: 14 }),
    safety: {},
  },

  // -------------------------------------------------------------------------
  // 3. THỊT & NỘI TẠNG (11)
  // -------------------------------------------------------------------------
  {
    id: 'thit-bo-nac',
    name: 'Thịt bò nạc',
    nameEn: 'Lean beef (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170629 (beef, lean, cooked) — sắt heme, kẽm, B12.',
    per100g: n({ kcal: 217, protein: 26, carb: 0, fat: 12, fiber: 0, iron: 2.7, calcium: 10, folate: 8, vitaminC: 0, vitaminD: 0, zinc: 5, iodine: 0, omega3: 15, sodium: 55, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-lon-nac',
    name: 'Thịt lợn nạc',
    nameEn: 'Lean pork (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 168253 (pork, lean, cooked) — đạm, kẽm, B1.',
    per100g: n({ kcal: 242, protein: 27, carb: 0, fat: 14, fiber: 0, iron: 1.1, calcium: 5, folate: 5, vitaminC: 0, vitaminD: 0, zinc: 2.9, iodine: 0, omega3: 0, sodium: 62, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-ga-uc',
    name: 'Ức gà',
    nameEn: 'Chicken breast (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170599 (roasted) — đạm cao, ít béo.',
    per100g: n({ kcal: 165, protein: 31, carb: 0, fat: 3.6, fiber: 0, iron: 1, calcium: 12, folate: 4, vitaminC: 0, vitaminD: 0, zinc: 1, iodine: 0, omega3: 20, sodium: 74, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-ga-ta',
    name: 'Gà ta (cả da)',
    nameEn: 'Chicken (with skin)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171102 (chicken, broiler, meat+skin, cooked).',
    per100g: n({ kcal: 239, protein: 24, carb: 0, fat: 15, fiber: 0, iron: 1.3, calcium: 12, folate: 6, vitaminC: 0, vitaminD: 0, zinc: 1.7, iodine: 0, omega3: 40, sodium: 76, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-vit',
    name: 'Thịt vịt',
    nameEn: 'Duck (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171457 (domesticated duck, meat+skin, roasted).',
    per100g: n({ kcal: 337, protein: 19, carb: 0, fat: 28, fiber: 0, iron: 2.7, calcium: 11, folate: 7, vitaminC: 0, vitaminD: 0, zinc: 2, iodine: 0, omega3: 50, sodium: 74, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-cuu',
    name: 'Thịt cừu',
    nameEn: 'Lamb (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172477 (lamb, cooked) — kẽm.',
    per100g: n({ kcal: 258, protein: 25, carb: 0, fat: 17, fiber: 0, iron: 1.6, calcium: 12, folate: 18, vitaminC: 0, vitaminD: 0, zinc: 4.1, iodine: 0, omega3: 70, sodium: 63, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'thit-tho',
    name: 'Thịt thỏ',
    nameEn: 'Rabbit (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171482 (rabbit, domesticated, roasted).',
    per100g: n({ kcal: 173, protein: 33, carb: 0, fat: 3.5, fiber: 0, iron: 2.3, calcium: 15, folate: 7, vitaminC: 0, vitaminD: 0, zinc: 2, iodine: 0, omega3: 0, sodium: 44, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'gan-ga',
    name: 'Gan gà',
    nameEn: 'Chicken liver (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172428 — retinol rất cao ~3.000–4.000 mcg RAE/100g (KB GĐ2).',
    per100g: n({ kcal: 167, protein: 25, carb: 0.9, fat: 6.6, fiber: 0, iron: 11, calcium: 10, folate: 578, vitaminC: 23, vitaminD: 0, zinc: 3.4, iodine: 0, omega3: 0, sodium: 58, sugar: 0 }),
    safety: { avoid: true, reason: 'Gan giàu retinol vượt UL thai kỳ — nguy cơ quái thai (nhất là T1). Tránh khi mang thai (NHS).' },
  },
  {
    id: 'gan-lon',
    name: 'Gan lợn',
    nameEn: 'Pork liver (cooked)',
    group: 'thit',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169208 — retinol cao, sắt & B12.',
    per100g: n({ kcal: 134, protein: 21, carb: 1.5, fat: 4.4, fiber: 0, iron: 18, calcium: 9, folate: 210, vitaminC: 23, vitaminD: 0, zinc: 5, iodine: 0, omega3: 0, sodium: 69, sugar: 0 }),
    safety: { avoid: true, reason: 'Gan giàu retinol — tránh khi mang thai; bổ máu nên thay bằng thịt bò/huyết/sò.' },
  },
  {
    id: 'huyet-lon',
    name: 'Huyết lợn (luộc)',
    nameEn: 'Pork blood (cooked)',
    group: 'thit',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng — sắt rất cao 9–30 mg/100g (KB).',
    per100g: n({ kcal: 58, protein: 12, carb: 0.4, fat: 0.3, fiber: 0, iron: 20, calcium: 10, folate: 5, vitaminC: 0, vitaminD: 0, zinc: 1.2, iodine: 0, omega3: 0, sodium: 120, sugar: 0 }),
    safety: { cook: true, reason: 'Chỉ ăn huyết luộc chín kỹ; TUYỆT ĐỐI không tiết canh sống (nhiễm khuẩn/liên cầu lợn).' },
  },
  {
    id: 'gio-heo',
    name: 'Giò lụa (chả lụa)',
    nameEn: 'Vietnamese pork sausage',
    group: 'thit',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng VN — natri cao.',
    per100g: n({ kcal: 270, protein: 18, carb: 5, fat: 20, fiber: 0, iron: 2, calcium: 15, folate: 4, vitaminC: 0, vitaminD: 0, zinc: 2, iodine: 0, omega3: 0, sodium: 900, sugar: 0 }),
    safety: { limit: true, reason: 'Chọn giò đảm bảo vệ sinh, ăn vừa phải (muối cao).' },
  },

  // -------------------------------------------------------------------------
  // 4. CÁ & HẢI SẢN (20)
  // -------------------------------------------------------------------------
  {
    id: 'ca-hoi',
    name: 'Cá hồi',
    nameEn: 'Salmon (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173692 (Atlantic, cooked) — DHA 2,3 g & vitamin D cao.',
    per100g: n({ kcal: 208, protein: 20, carb: 0, fat: 13, fiber: 0, iron: 0.3, calcium: 9, folate: 4, vitaminC: 0, vitaminD: 11, zinc: 0.4, iodine: 7, omega3: 2300, sodium: 59, sugar: 0 }),
    safety: { reason: 'Cá béo ít thủy ngân — 2 phần/tuần (FDA/EPA).' },
  },
  {
    id: 'ca-thu',
    name: 'Cá thu',
    nameEn: 'Mackerel (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173670 (Atlantic mackerel, cooked) — DHA 2,6 g.',
    per100g: n({ kcal: 262, protein: 24, carb: 0, fat: 18, fiber: 0, iron: 1.6, calcium: 9, folate: 1, vitaminC: 0, vitaminD: 16, zinc: 0.9, iodine: 8, omega3: 2600, sodium: 90, sugar: 0 }),
    safety: { reason: 'Cá béo ít thủy ngân — ưu tiên T2/T3 cho DHA.' },
  },
  {
    id: 'ca-moi',
    name: 'Cá mòi (hộp)',
    nameEn: 'Sardine (canned)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175127 (sardine, canned in oil) — ăn cả xương, giàu canxi 382 mg.',
    per100g: n({ kcal: 208, protein: 25, carb: 0, fat: 11, fiber: 0, iron: 2.9, calcium: 382, folate: 10, vitaminC: 0, vitaminD: 4.8, zinc: 1.3, iodine: 16, omega3: 1500, sodium: 307, sugar: 0 }),
    safety: { reason: 'Giàu canxi & DHA — ăn cả xương khi kho.' },
  },
  {
    id: 'ca-chem',
    name: 'Cá chẽm (vược)',
    nameEn: 'Barramundi (cooked)',
    group: 'ca-hai-san',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo USDA barramundi — cá trắng ít béo.',
    per100g: n({ kcal: 113, protein: 23, carb: 0, fat: 2.3, fiber: 0, iron: 0.4, calcium: 10, folate: 5, vitaminC: 0, vitaminD: 1, zinc: 0.5, iodine: 8, omega3: 260, sodium: 56, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-ro-phi',
    name: 'Cá rô phi',
    nameEn: 'Tilapia (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175116 (tilapia, cooked) — ít thủy ngân (FDA "best choice").',
    per100g: n({ kcal: 128, protein: 26, carb: 0, fat: 2.7, fiber: 0, iron: 0.6, calcium: 10, folate: 7, vitaminC: 0, vitaminD: 0.4, zinc: 0.4, iodine: 6, omega3: 150, sodium: 52, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-chep',
    name: 'Cá chép',
    nameEn: 'Carp (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 174101 (carp, cooked).',
    per100g: n({ kcal: 162, protein: 22, carb: 0, fat: 7.6, fiber: 0, iron: 1.5, calcium: 18, folate: 15, vitaminC: 0, vitaminD: 0.6, zinc: 1.3, iodine: 7, omega3: 300, sodium: 49, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-tram',
    name: 'Cá trắm cỏ',
    nameEn: 'Grass carp (cooked)',
    group: 'ca-hai-san',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo USDA carp — cá nước ngọt VN.',
    per100g: n({ kcal: 127, protein: 24, carb: 0, fat: 3, fiber: 0, iron: 1, calcium: 25, folate: 10, vitaminC: 0, vitaminD: 0.3, zinc: 1, iodine: 7, omega3: 200, sodium: 48, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-basa',
    name: 'Cá basa',
    nameEn: 'Pangasius / basa (cooked)',
    group: 'ca-hai-san',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo USDA pangasius — cá trắng giá rẻ.',
    per100g: n({ kcal: 121, protein: 21, carb: 0, fat: 3.7, fiber: 0, iron: 0.3, calcium: 9, folate: 6, vitaminC: 0, vitaminD: 0.2, zinc: 0.4, iodine: 6, omega3: 150, sodium: 46, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-loc',
    name: 'Cá lóc',
    nameEn: 'Snakehead fish (cooked)',
    group: 'ca-hai-san',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng VN — cá nước ngọt phổ biến.',
    per100g: n({ kcal: 130, protein: 25, carb: 0, fat: 3, fiber: 0, iron: 1.5, calcium: 20, folate: 8, vitaminC: 0, vitaminD: 0.3, zinc: 0.9, iodine: 7, omega3: 180, sodium: 50, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ca-nuc',
    name: 'Cá cơm',
    nameEn: 'Anchovy (canned)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175099 (anchovy, canned) — DHA 1,4 g, canxi cao.',
    per100g: n({ kcal: 131, protein: 20, carb: 0, fat: 4.8, fiber: 0, iron: 3.3, calcium: 232, folate: 9, vitaminC: 0, vitaminD: 0.8, zinc: 1.7, iodine: 20, omega3: 1400, sodium: 3668, sugar: 0 }),
    safety: { limit: true, reason: 'Rất mặn (natri cao) — dùng vừa, kho ngọt để giảm muối.' },
  },
  {
    id: 'ca-ngu',
    name: 'Cá ngừ (đóng hộp, light)',
    nameEn: 'Tuna (canned light)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 15126 (tuna, light, canned in water) — thủy ngân thấp hơn cá ngừ tươi.',
    per100g: n({ kcal: 132, protein: 28, carb: 0, fat: 1.3, fiber: 0, iron: 1.3, calcium: 15, folate: 4, vitaminC: 0, vitaminD: 1, zinc: 0.6, iodine: 20, omega3: 150, sodium: 250, sugar: 0 }),
    safety: { limit: true, reason: 'Cá ngừ có thủy ngân — giới hạn ≤1 hộp/tuần; tránh cá ngừ mắt to/albacore.' },
  },
  {
    id: 'ca-kiem',
    name: 'Cá kiếm',
    nameEn: 'Swordfish',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172452 (swordfish, cooked).',
    per100g: n({ kcal: 121, protein: 20, carb: 0, fat: 4, fiber: 0, iron: 0.7, calcium: 8, folate: 2, vitaminC: 0, vitaminD: 0.7, zinc: 0.7, iodine: 20, omega3: 700, sodium: 81, sugar: 0 }),
    safety: { avoid: true, reason: 'Thủy ngân rất cao — tránh tuyệt đối khi mang thai (FDA/EPA).' },
  },
  {
    id: 'ca-map',
    name: 'Cá mập',
    nameEn: 'Shark',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC — nhóm cá thủy ngân rất cao.',
    per100g: n({ kcal: 130, protein: 21, carb: 0, fat: 4.5, fiber: 0, iron: 1, calcium: 45, folate: 2, vitaminC: 0, vitaminD: 0.5, zinc: 0.5, iodine: 20, omega3: 600, sodium: 78, sugar: 0 }),
    safety: { avoid: true, reason: 'Thủy ngân rất cao — tránh tuyệt đối khi mang thai (FDA/EPA).' },
  },
  {
    id: 'tom',
    name: 'Tôm',
    nameEn: 'Shrimp (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175175 (shrimp, cooked) — i-ốt, kẽm.',
    per100g: n({ kcal: 99, protein: 24, carb: 0.2, fat: 0.3, fiber: 0, iron: 0.5, calcium: 70, folate: 3, vitaminC: 0, vitaminD: 0.1, zinc: 1.6, iodine: 10, omega3: 200, sodium: 111, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'tom-hum',
    name: 'Tôm hùm',
    nameEn: 'Lobster (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173021 (lobster, cooked) — kẽm.',
    per100g: n({ kcal: 89, protein: 19, carb: 0, fat: 0.9, fiber: 0, iron: 0.3, calcium: 90, folate: 11, vitaminC: 0, vitaminD: 0.1, zinc: 4, iodine: 10, omega3: 100, sodium: 296, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'cua',
    name: 'Cua',
    nameEn: 'Crab (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172164 (crab, cooked) — kẽm, folate.',
    per100g: n({ kcal: 87, protein: 19, carb: 0, fat: 0.7, fiber: 0, iron: 0.5, calcium: 86, folate: 44, vitaminC: 3, vitaminD: 0.2, zinc: 3.6, iodine: 14, omega3: 250, sodium: 293, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'ngheu',
    name: 'Nghêu (sò)',
    nameEn: 'Clam (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171694 (clam, cooked) — sắt 28 mg, B12 84 mcg.',
    per100g: n({ kcal: 148, protein: 25, carb: 5, fat: 1.9, fiber: 0, iron: 28, calcium: 92, folate: 19, vitaminC: 13, vitaminD: 0.2, zinc: 2.7, iodine: 30, omega3: 150, sodium: 56, sugar: 0 }),
    safety: { cook: true, reason: 'Ăn chín kỹ; không ăn hải sản sống.' },
  },
  {
    id: 'hau',
    name: 'Hàu',
    nameEn: 'Oyster (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171158 (oyster, cooked) — kẽm rất cao 39–78 mg.',
    per100g: n({ kcal: 68, protein: 7, carb: 3.9, fat: 2.5, fiber: 0, iron: 5.5, calcium: 37, folate: 14, vitaminC: 0, vitaminD: 0.1, zinc: 39, iodine: 25, omega3: 300, sodium: 106, sugar: 0 }),
    safety: { cook: true, reason: 'Ăn chín kỹ; hàu sống nguy cơ Vibrio — tránh.' },
  },
  {
    id: 'muc',
    name: 'Mực',
    nameEn: 'Squid (cooked)',
    group: 'ca-hai-san',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173709 (squid, cooked).',
    per100g: n({ kcal: 92, protein: 16, carb: 3, fat: 1.4, fiber: 0, iron: 0.7, calcium: 36, folate: 5, vitaminC: 0, vitaminD: 0, zinc: 1.7, iodine: 10, omega3: 400, sodium: 260, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'rong-bien',
    name: 'Rong biển (khô)',
    nameEn: 'Seaweed (kelp, dried)',
    group: 'ca-hai-san',
    accuracy: 'estimate',
    sourceNote: 'I-ốt biến thiên rất lớn, có thể >1.000 mcg/100g — dùng rất ít (KB GĐ2).',
    per100g: n({ kcal: 43, protein: 1.7, carb: 10, fat: 0.6, fiber: 1.3, iron: 2.9, calcium: 168, folate: 53, vitaminC: 3, vitaminD: 0, zinc: 1.2, iodine: 2000, omega3: 0, sodium: 872, sugar: 0 }),
    safety: { limit: true, reason: 'I-ốt rất cao — không ăn hàng ngày; ATA: tránh sản phẩm >500 mcg i-ốt/ngày.' },
  },

  // -------------------------------------------------------------------------
  // 5. TRỨNG & SỮA (8)
  // -------------------------------------------------------------------------
  {
    id: 'trung-ga',
    name: 'Trứng gà',
    nameEn: 'Chicken egg (cooked)',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171287 (whole egg, cooked) — lòng đỏ giàu choline ~147 mg/quả.',
    per100g: n({ kcal: 155, protein: 13, carb: 1.1, fat: 11, fiber: 0, iron: 1.2, calcium: 50, folate: 44, vitaminC: 0, vitaminD: 2.2, zinc: 1.3, iodine: 25, omega3: 40, sodium: 124, sugar: 0 }),
    safety: { cook: true, reason: 'Ăn chín kỹ; không trứng chần/lòng đào khi mang thai.' },
  },
  {
    id: 'trung-vit',
    name: 'Trứng vịt',
    nameEn: 'Duck egg',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 174278 (duck egg, raw) — sắt & folate cao hơn trứng gà.',
    per100g: n({ kcal: 185, protein: 13, carb: 1.5, fat: 14, fiber: 0, iron: 3.8, calcium: 64, folate: 80, vitaminC: 0, vitaminD: 2.5, zinc: 1.4, iodine: 25, omega3: 60, sodium: 146, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'sua-bo-tuoi',
    name: 'Sữa bò tươi',
    nameEn: 'Whole milk',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171265 (whole milk, 3,25%) — canxi 113 mg, i-ốt 50–80 mcg.',
    per100g: n({ kcal: 61, protein: 3.2, carb: 4.8, fat: 3.3, fiber: 0, iron: 0, calcium: 113, folate: 5, vitaminC: 0, vitaminD: 1, zinc: 0.4, iodine: 50, omega3: 0, sodium: 43, sugar: 5 }),
    safety: { reason: 'Chọn sữa tiệt trùng/pasteur.' },
  },
  {
    id: 'sua-chua',
    name: 'Sữa chua',
    nameEn: 'Yogurt (plain)',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171285 (yogurt, plain, whole) — canxi 121 mg.',
    per100g: n({ kcal: 59, protein: 3.5, carb: 4.7, fat: 3.3, fiber: 0, iron: 0, calcium: 121, folate: 7, vitaminC: 0.5, vitaminD: 0.2, zinc: 0.6, iodine: 25, omega3: 0, sodium: 46, sugar: 4.7 }),
    safety: {},
  },
  {
    id: 'pho-mai',
    name: 'Phô mai (cheddar)',
    nameEn: 'Cheddar cheese',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171282 (cheddar) — canxi 721 mg.',
    per100g: n({ kcal: 403, protein: 25, carb: 1.3, fat: 33, fiber: 0, iron: 0.5, calcium: 721, folate: 18, vitaminC: 0, vitaminD: 0.6, zinc: 3.1, iodine: 40, omega3: 0, sodium: 621, sugar: 0.5 }),
    safety: { reason: 'Chọn phô mai tiệt trùng; tránh phô mai mốc/lên men mềm (nhập khẩu).' },
  },
  {
    id: 'sua-bo-tang-cuong',
    name: 'Sữa bò tăng cường (vit D)',
    nameEn: 'Fortified milk (vitamin D)',
    group: 'trung-sua',
    accuracy: 'estimate',
    sourceNote: 'Sữa tiệt trùng VN thường bổ sung vitamin D & canxi — KB khuyến nghị ở VN.',
    per100g: n({ kcal: 61, protein: 3.2, carb: 4.8, fat: 3.3, fiber: 0, iron: 0.2, calcium: 130, folate: 10, vitaminC: 1, vitaminD: 2.5, zinc: 0.5, iodine: 50, omega3: 0, sodium: 45, sugar: 5 }),
    safety: {},
  },
  {
    id: 'sua-dau-nanh',
    name: 'Sữa đậu nành',
    nameEn: 'Soy milk',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175168 (soy milk) — lựa chọn cho người không dung nạp lactose.',
    per100g: n({ kcal: 54, protein: 3.3, carb: 6.3, fat: 1.8, fiber: 0.6, iron: 0.4, calcium: 15, folate: 20, vitaminC: 0, vitaminD: 0.9, zinc: 0.3, iodine: 5, omega3: 30, sodium: 51, sugar: 6 }),
    safety: {},
  },
  {
    id: 'bo-nuoc',
    name: 'Bơ (chất béo sữa)',
    nameEn: 'Butter',
    group: 'trung-sua',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171414 (butter, salted) — dùng lượng nhỏ.',
    per100g: n({ kcal: 717, protein: 0.9, carb: 0.1, fat: 81, fiber: 0, iron: 0, calcium: 24, folate: 3, vitaminC: 0, vitaminD: 0, zinc: 0.1, iodine: 10, omega3: 0, sodium: 11, sugar: 0.1 }),
    safety: {},
  },

  // -------------------------------------------------------------------------
  // 6. ĐẬU, HẠT, NẤM (16)
  // -------------------------------------------------------------------------
  {
    id: 'dau-phu',
    name: 'Đậu phụ (đông đặc canxi)',
    nameEn: 'Tofu (firm, calcium-set)',
    group: 'dau-hat',
    accuracy: 'estimate',
    sourceNote: 'KB GĐ2: canxi đông đặc ~130–350 mg/100g — nguồn canxi thực vật tốt.',
    per100g: n({ kcal: 76, protein: 8, carb: 1.9, fat: 4.8, fiber: 0.3, iron: 1.5, calcium: 200, folate: 15, vitaminC: 0, vitaminD: 0, zinc: 1, iodine: 0, omega3: 200, sodium: 7, sugar: 0.6 }),
    safety: { cook: true, reason: 'Đậu phụ nấu chín trước khi ăn.' },
  },
  {
    id: 'dau-nanh',
    name: 'Đậu nành (hạt nấu chín)',
    nameEn: 'Soybean (cooked)',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 174268 (soybeans, mature, boiled) — đạm, omega-3 thực vật.',
    per100g: n({ kcal: 173, protein: 16.6, carb: 9.9, fat: 9, fiber: 6, iron: 5.1, calcium: 102, folate: 54, vitaminC: 0, vitaminD: 0, zinc: 1, iodine: 0, omega3: 700, sodium: 1, sugar: 3 }),
    safety: { cook: true },
  },
  {
    id: 'dau-den',
    name: 'Đậu đen (nấu chín)',
    nameEn: 'Black bean (cooked)',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173743 (black beans, boiled) — sắt, chất xơ.',
    per100g: n({ kcal: 132, protein: 8.9, carb: 24, fat: 0.5, fiber: 8.7, iron: 2.1, calcium: 27, folate: 128, vitaminC: 0, vitaminD: 0, zinc: 1.1, iodine: 0, omega3: 0, sodium: 1, sugar: 0.3 }),
    safety: { cook: true },
  },
  {
    id: 'dau-xanh-hat',
    name: 'Đậu xanh (hạt khô)',
    nameEn: 'Mung bean (dry)',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 175205 (mung beans, raw) — folate 625 mcg/100g khô.',
    per100g: n({ kcal: 347, protein: 24, carb: 63, fat: 1.2, fiber: 16, iron: 6.7, calcium: 132, folate: 625, vitaminC: 0, vitaminD: 0, zinc: 2.7, iodine: 0, omega3: 0, sodium: 15, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'dau-do',
    name: 'Đậu đỏ (hạt khô)',
    nameEn: 'Red / adzuki bean (dry)',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 174278 (adzuki beans, raw) — folate 622 mcg.',
    per100g: n({ kcal: 329, protein: 20, carb: 63, fat: 0.5, fiber: 12.7, iron: 5, calcium: 66, folate: 622, vitaminC: 0, vitaminD: 0, zinc: 4, iodine: 0, omega3: 0, sodium: 18, sugar: 0 }),
    safety: { cook: true },
  },
  {
    id: 'dau-phong',
    name: 'Đậu phộng (lạc)',
    nameEn: 'Peanut',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172430 (peanuts, raw) — protein, folate, chất béo lành.',
    per100g: n({ kcal: 567, protein: 26, carb: 16, fat: 49, fiber: 8.5, iron: 4.6, calcium: 92, folate: 240, vitaminC: 0, vitaminD: 0, zinc: 3.3, iodine: 0, omega3: 0, sodium: 18, sugar: 4.7 }),
    safety: { reason: 'Chọn lạc không mốc (aflatoxin).' },
  },
  {
    id: 'vung',
    name: 'Vừng (mè)',
    nameEn: 'Sesame seeds',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170154 (sesame seeds, whole) — canxi 975 mg/100g.',
    per100g: n({ kcal: 573, protein: 18, carb: 23, fat: 50, fiber: 12, iron: 14.6, calcium: 975, folate: 97, vitaminC: 0, vitaminD: 0, zinc: 7.8, iodine: 0, omega3: 0, sodium: 11, sugar: 0.3 }),
    safety: {},
  },
  {
    id: 'hat-huong-duong',
    name: 'Hạt hướng dương',
    nameEn: 'Sunflower seeds',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170554 (sunflower seed kernels) — folate, vitamin E.',
    per100g: n({ kcal: 584, protein: 21, carb: 20, fat: 51, fiber: 8.6, iron: 5.3, calcium: 78, folate: 227, vitaminC: 1, vitaminD: 0, zinc: 5, iodine: 0, omega3: 0, sodium: 9, sugar: 2.6 }),
    safety: {},
  },
  {
    id: 'hat-bi',
    name: 'Hạt bí ngô',
    nameEn: 'Pumpkin seeds',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170556 (pumpkin seed kernels) — kẽm, sắt.',
    per100g: n({ kcal: 559, protein: 30, carb: 11, fat: 49, fiber: 6, iron: 8.8, calcium: 46, folate: 58, vitaminC: 2, vitaminD: 0, zinc: 7.8, iodine: 0, omega3: 0, sodium: 7, sugar: 1.4 }),
    safety: {},
  },
  {
    id: 'hat-dieu',
    name: 'Hạt điều',
    nameEn: 'Cashew',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170162 (cashew nuts) — kẽm, sắt.',
    per100g: n({ kcal: 553, protein: 18, carb: 33, fat: 44, fiber: 3.3, iron: 6.7, calcium: 37, folate: 25, vitaminC: 0, vitaminD: 0, zinc: 5.8, iodine: 0, omega3: 0, sodium: 12, sugar: 5.9 }),
    safety: {},
  },
  {
    id: 'hat-ha-nhan',
    name: 'Hạnh nhân',
    nameEn: 'Almond',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170567 (almonds) — canxi, vitamin E.',
    per100g: n({ kcal: 579, protein: 21, carb: 22, fat: 50, fiber: 12.5, iron: 3.7, calcium: 269, folate: 44, vitaminC: 0, vitaminD: 0, zinc: 3.1, iodine: 0, omega3: 0, sodium: 1, sugar: 4.4 }),
    safety: {},
  },
  {
    id: 'hat-ocho-cho',
    name: 'Óc chó',
    nameEn: 'Walnut',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170581 (walnuts) — ALA omega-3 thực vật ~9 g/100g.',
    per100g: n({ kcal: 654, protein: 15, carb: 14, fat: 65, fiber: 6.7, iron: 2.9, calcium: 98, folate: 98, vitaminC: 1, vitaminD: 0, zinc: 3.1, iodine: 0, omega3: 9000, sodium: 2, sugar: 2.6 }),
    safety: {},
  },
  {
    id: 'hat-de-cuoi',
    name: 'Hạt dẻ cười',
    nameEn: 'Pistachio',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170181 (pistachio) — chất xơ, vitamin B6.',
    per100g: n({ kcal: 560, protein: 20, carb: 28, fat: 45, fiber: 10, iron: 3.9, calcium: 105, folate: 51, vitaminC: 0, vitaminD: 0, zinc: 2.2, iodine: 0, omega3: 0, sodium: 1, sugar: 7.7 }),
    safety: {},
  },
  {
    id: 'nam-rom',
    name: 'Nấm rơm',
    nameEn: 'Straw mushroom',
    group: 'dau-hat',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng — nấm nhiệt đới VN.',
    per100g: n({ kcal: 33, protein: 3.5, carb: 4, fat: 0.4, fiber: 2.4, iron: 1.5, calcium: 5, folate: 30, vitaminC: 3, vitaminD: 0.2, zinc: 0.8, iodine: 0, omega3: 0, sodium: 5, sugar: 1.5 }),
    safety: { cook: true },
  },
  {
    id: 'nam-dong-co',
    name: 'Nấm đông cô',
    nameEn: 'Shiitake (cooked)',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169845 (shiitake, cooked) — vitamin D nếu phơi nắng.',
    per100g: n({ kcal: 34, protein: 2.2, carb: 6.8, fat: 0.5, fiber: 2.5, iron: 0.6, calcium: 3, folate: 13, vitaminC: 1, vitaminD: 0.3, zinc: 0.9, iodine: 0, omega3: 0, sodium: 5, sugar: 2.4 }),
    safety: { cook: true },
  },
  {
    id: 'nam-mo',
    name: 'Nấm mỡ (nấm tươi)',
    nameEn: 'Button mushroom',
    group: 'dau-hat',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169262 (mushrooms, white, cooked).',
    per100g: n({ kcal: 22, protein: 3.1, carb: 3.3, fat: 0.3, fiber: 1, iron: 0.5, calcium: 3, folate: 17, vitaminC: 2, vitaminD: 0.2, zinc: 0.5, iodine: 0, omega3: 0, sodium: 5, sugar: 2 }),
    safety: { cook: true },
  },

  // -------------------------------------------------------------------------
  // 7. NGŨ CỐC (14)
  // -------------------------------------------------------------------------
  {
    id: 'gao-trang',
    name: 'Gạo trắng (khô)',
    nameEn: 'White rice (dry)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — gạo tẻ máy; dùng tính cháo/xôi.',
    per100g: n({ kcal: 344, protein: 7.9, carb: 75.9, fat: 1.0, fiber: 0.4, iron: 1.3, calcium: 30, folate: 9, vitaminC: 0, vitaminD: 0, zinc: 1.5, iodine: 0, omega3: 0, sodium: 5, sugar: 0.1 }),
    safety: { cook: true },
  },
  {
    id: 'com-trang',
    name: 'Cơm trắng (chín)',
    nameEn: 'Cooked white rice',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169759 (white rice, cooked) — năng lượng chính bữa ăn.',
    per100g: n({ kcal: 130, protein: 2.7, carb: 28, fat: 0.3, fiber: 0.4, iron: 0.2, calcium: 3, folate: 3, vitaminC: 0, vitaminD: 0, zinc: 0.5, iodine: 0, omega3: 0, sodium: 1, sugar: 0.1 }),
    safety: {},
  },
  {
    id: 'gao-lut',
    name: 'Gạo lứt (chín)',
    nameEn: 'Cooked brown rice',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169761 (brown rice, cooked) — chất xơ hơn gạo trắng.',
    per100g: n({ kcal: 112, protein: 2.3, carb: 24, fat: 0.8, fiber: 1.8, iron: 0.5, calcium: 6, folate: 4, vitaminC: 0, vitaminD: 0, zinc: 0.6, iodine: 0, omega3: 0, sodium: 4, sugar: 0.4 }),
    safety: {},
  },
  {
    id: 'gao-nep',
    name: 'Gạo nếp (khô)',
    nameEn: 'Glutinous rice (dry)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — gạo nếp cái; dùng cho xôi.',
    per100g: n({ kcal: 344, protein: 8.6, carb: 74.5, fat: 1.5, fiber: 0.6, iron: 1.2, calcium: 32, folate: 7, vitaminC: 0, vitaminD: 0, zinc: 2.2, iodine: 0, omega3: 0, sodium: 3, sugar: 0.1 }),
    safety: { cook: true },
  },
  {
    id: 'banh-mi-trang',
    name: 'Bánh mì trắng',
    nameEn: 'White bread (French bread, VN)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — bánh mỳ (ổ bánh mì VN).',
    per100g: n({ kcal: 249, protein: 7.9, carb: 52.6, fat: 0.8, fiber: 0.2, iron: 2.0, calcium: 28, folate: 77, vitaminC: 0, vitaminD: 0, zinc: 1.2, iodine: 0, omega3: 0, sodium: 491, sugar: 5 }),
    safety: {},
  },
  {
    id: 'banh-mi-nguyen-cam',
    name: 'Bánh mì nguyên cám',
    nameEn: 'Whole-wheat bread',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 173970 (whole-wheat bread) — chất xơ.',
    per100g: n({ kcal: 247, protein: 13, carb: 41, fat: 3.4, fiber: 7, iron: 2.5, calcium: 80, folate: 30, vitaminC: 0, vitaminD: 0, zinc: 1.8, iodine: 0, omega3: 0, sodium: 400, sugar: 6 }),
    safety: {},
  },
  {
    id: 'bun-tuoi',
    name: 'Bún tươi',
    nameEn: 'Rice vermicelli (cooked)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — bún (bán ướt).',
    per100g: n({ kcal: 110, protein: 1.7, carb: 25.7, fat: 0.1, fiber: 0.5, iron: 0.2, calcium: 12, folate: 2, vitaminC: 0, vitaminD: 0, zinc: 0.3, iodine: 0, omega3: 0, sodium: 15, sugar: 0 }),
    safety: {},
  },
  {
    id: 'banh-pho',
    name: 'Bánh phở (bánh ướt)',
    nameEn: 'Flat rice noodles (cooked)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — bánh phở.',
    per100g: n({ kcal: 143, protein: 3.2, carb: 31.7, fat: 0.4, fiber: 0, iron: 0.3, calcium: 16, folate: 2, vitaminC: 0, vitaminD: 0, zinc: 0.3, iodine: 0, omega3: 0, sodium: 3, sugar: 0 }),
    safety: {},
  },
  {
    id: 'mi-soi',
    name: 'Mì sợi (nấu chín)',
    nameEn: 'Wheat noodles (cooked)',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169704 (noodles, egg, enriched, cooked).',
    per100g: n({ kcal: 138, protein: 4.5, carb: 25, fat: 2.1, fiber: 1.2, iron: 1.1, calcium: 12, folate: 6, vitaminC: 0, vitaminD: 0, zinc: 0.7, iodine: 0, omega3: 0, sodium: 215, sugar: 0.4 }),
    safety: { cook: true },
  },
  {
    id: 'yen-mach',
    name: 'Yến mạch (chín)',
    nameEn: 'Oatmeal (cooked)',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171656 (oats, cooked) — chất xơ hòa tan.',
    per100g: n({ kcal: 71, protein: 2.5, carb: 12, fat: 1.5, fiber: 1.7, iron: 0.9, calcium: 9, folate: 6, vitaminC: 0, vitaminD: 0, zinc: 1, iodine: 0, omega3: 0, sodium: 4, sugar: 0.3 }),
    safety: {},
  },
  {
    id: 'yen-mach-kho',
    name: 'Yến mạch (khô)',
    nameEn: 'Rolled oats (dry)',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 171660 (oats, rolled, dry) — dùng tính ngũ cốc/cháo.',
    per100g: n({ kcal: 389, protein: 17, carb: 66, fat: 6.9, fiber: 10, iron: 4.7, calcium: 54, folate: 56, vitaminC: 0, vitaminD: 0, zinc: 3, iodine: 0, omega3: 0, sodium: 6, sugar: 0.9 }),
    safety: {},
  },
  {
    id: 'ngo-luoc',
    name: 'Ngô (bắp) luộc',
    nameEn: 'Glutinous maize (boiled)',
    group: 'ngu-coc',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — ngô nếp luộc.',
    per100g: n({ kcal: 167, protein: 3.9, carb: 32.9, fat: 2.2, fiber: 1.2, iron: 0.8, calcium: 18, folate: 23, vitaminC: 0, vitaminD: 0, zinc: 0.6, iodine: 0, omega3: 0, sodium: 15, sugar: 4.5 }),
    safety: {},
  },
  {
    id: 'khoai-mi',
    name: 'Khoai mì (sắn, chín)',
    nameEn: 'Cassava (cooked)',
    group: 'ngu-coc',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170522 (cassava, cooked) — năng lượng, tinh bột.',
    per100g: n({ kcal: 112, protein: 1.1, carb: 27, fat: 0.3, fiber: 1.6, iron: 0.3, calcium: 16, folate: 10, vitaminC: 20, vitaminD: 0, zinc: 0.3, iodine: 0, omega3: 0, sodium: 14, sugar: 1 }),
    safety: { cook: true, reason: 'Sắn phải gọt vỏ, nấu chín kỹ để loại cyanide — không ăn sống.' },
  },
  {
    id: 'banh-trang',
    name: 'Bánh tráng (bánh đa nem)',
    nameEn: 'Rice paper',
    group: 'ngu-coc',
    accuracy: 'estimate',
    sourceNote: 'Ước tính theo CSDL dinh dưỡng — bánh tráng gạo VN.',
    per100g: n({ kcal: 340, protein: 4.5, carb: 72, fat: 1, fiber: 3, iron: 2, calcium: 10, folate: 2, vitaminC: 0, vitaminD: 0, zinc: 0.5, iodine: 0, omega3: 0, sodium: 120, sugar: 0 }),
    safety: { reason: 'Bánh tráng gói cuốn cần dùng loại sản xuất sạch; ngâm nước sạch.' },
  },

  // -------------------------------------------------------------------------
  // 8. GIA VỊ (10)
  // -------------------------------------------------------------------------
  {
    id: 'muoi-iot',
    name: 'Muối i-ốt',
    nameEn: 'Iodized salt',
    group: 'gia-vi',
    accuracy: 'estimate',
    sourceNote: 'Muối tăng cường ~25–30 mg i-ốt/kg → 2–3 g/ngày cho ~50–80 mcg i-ốt (KB).',
    per100g: n({ kcal: 0, protein: 0, carb: 0, fat: 0, fiber: 0, iron: 0, calcium: 0, folate: 0, vitaminC: 0, vitaminD: 0, zinc: 0, iodine: 2600, omega3: 0, sodium: 38700, sugar: 0 }),
    safety: { reason: 'Dùng muối i-ốt hằng ngày cho gia đình khi nấu ăn.' },
  },
  {
    id: 'nuoc-mam',
    name: 'Nước mắm',
    nameEn: 'Fish sauce',
    group: 'gia-vi',
    accuracy: 'VN-KB',
    sourceNote: 'Bảng thành phần TP VN (Viện Dinh dưỡng) 2007 — nước mắm cá (natri rất cao).',
    per100g: n({ kcal: 35, protein: 5.1, carb: 3.6, fat: 0, fiber: 0, iron: 0.78, calcium: 43, folate: 0, vitaminC: 1, vitaminD: 0, zinc: 0.2, iodine: 20, omega3: 0, sodium: 7720, sugar: 0.9 }),
    safety: { reason: 'Mặn (natri cao) — dùng vừa phải.' },
  },
  {
    id: 'toi',
    name: 'Tỏi',
    nameEn: 'Garlic',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169222 (raw).',
    per100g: n({ kcal: 149, protein: 6.4, carb: 33, fat: 0.5, fiber: 2.1, iron: 1.7, calcium: 181, folate: 3, vitaminC: 31, vitaminD: 0, zinc: 1.2, iodine: 0, omega3: 0, sodium: 17, sugar: 1 }),
    safety: {},
  },
  {
    id: 'hanh-tay',
    name: 'Hành tây',
    nameEn: 'Onion',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 169295 (raw).',
    per100g: n({ kcal: 40, protein: 1.1, carb: 9.3, fat: 0.1, fiber: 1.7, iron: 0.2, calcium: 23, folate: 19, vitaminC: 7.4, vitaminD: 0, zinc: 0.2, iodine: 0, omega3: 0, sodium: 4, sugar: 4.2 }),
    safety: {},
  },
  {
    id: 'gung',
    name: 'Gừng',
    nameEn: 'Ginger',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 11216 (raw) — hỗ trợ giảm buồn nôn ốm nghén (KB).',
    per100g: n({ kcal: 80, protein: 1.8, carb: 18, fat: 0.8, fiber: 2, iron: 0.6, calcium: 16, folate: 11, vitaminC: 5, vitaminD: 0, zinc: 0.3, iodine: 0, omega3: 0, sodium: 13, sugar: 1.7 }),
    safety: { reason: 'Vài lát gừng/ngày an toàn giúp giảm buồn nôn.' },
  },
  {
    id: 'nghe',
    name: 'Nghệ',
    nameEn: 'Turmeric',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 172210 (turmeric, ground) — dùng làm gia vị lượng nhỏ.',
    per100g: n({ kcal: 354, protein: 7.8, carb: 65, fat: 3.3, fiber: 21, iron: 41, calcium: 183, folate: 38, vitaminC: 0, vitaminD: 0, zinc: 4.4, iodine: 0, omega3: 0, sodium: 38, sugar: 3.2 }),
    safety: { limit: true, reason: 'Chỉ dùng làm gia vị; không dùng tinh chất/liều cao khi mang thai.' },
  },
  {
    id: 'ot',
    name: 'Ớt tươi',
    nameEn: 'Chili pepper (fresh)',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 170534 (chili, red, raw) — vitamin C.',
    per100g: n({ kcal: 40, protein: 1.9, carb: 8.8, fat: 0.4, fiber: 1.5, iron: 1.2, calcium: 14, folate: 23, vitaminC: 144, vitaminD: 0, zinc: 0.3, iodine: 0, omega3: 0, sodium: 9, sugar: 5.3 }),
    safety: { limit: true, reason: 'Ăn ít nếu bị ợ nóng/trào ngược thai kỳ.' },
  },
  {
    id: 'dau-an-thuc-vat',
    name: 'Dầu thực vật',
    nameEn: 'Vegetable oil',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC — dầu thực vật tinh luyện (năng lượng, chất béo).',
    per100g: n({ kcal: 884, protein: 0, carb: 0, fat: 100, fiber: 0, iron: 0, calcium: 0, folate: 0, vitaminC: 0, vitaminD: 0, zinc: 0, iodine: 0, omega3: 0, sodium: 0, sugar: 0 }),
    safety: {},
  },
  {
    id: 'mat-ong',
    name: 'Mật ong',
    nameEn: 'Honey',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 19296 (honey) — đường tự nhiên.',
    per100g: n({ kcal: 304, protein: 0.3, carb: 82, fat: 0, fiber: 0.2, iron: 0.4, calcium: 6, folate: 2, vitaminC: 0.5, vitaminD: 0, zinc: 0.2, iodine: 0, omega3: 0, sodium: 4, sugar: 82 }),
    safety: { reason: 'Chọn mật ong đã tiệt trùng; hạn chế nếu tiểu đường thai kỳ.' },
  },
  {
    id: 'duong-trang',
    name: 'Đường trắng',
    nameEn: 'White sugar',
    group: 'gia-vi',
    accuracy: 'USDA',
    sourceNote: 'USDA FDC 19335 (sugar, granulated) — năng lượng rỗng.',
    per100g: n({ kcal: 387, protein: 0, carb: 100, fat: 0, fiber: 0, iron: 0, calcium: 1, folate: 0, vitaminC: 0, vitaminD: 0, zinc: 0, iodine: 0, omega3: 0, sodium: 1, sugar: 100 }),
    safety: { limit: true, reason: 'Hạn chế đường nếu tiểu đường thai kỳ/tăng cân quá mức.' },
  },
]

/** Tra nhanh thực phẩm theo id. Trả undefined nếu không tồn tại. */
export function getFood(id: string): FoodItem | undefined {
  return FOODS.find((f) => f.id === id)
}
